### ISSUE TITLE
Global ExecutionContext should not be used

### ISSUE THREAD

**Issue by bytecodeguru** [buildo/backend#14]
https://github.com/buildo/toctoc/blob/da8b0a789d4bd14149d7ec48b39b1af5d94deb7f/backend/core/src/main/scala/io.buildo.toctoc/core/authentication/AuthenticationDomain.scala#L9

ExecutionContext should be an implicit parameter of `AuthenticationDomain.exchangeCredentials`.

This stems from the fact that toctoc is not using a generic effect monad instead of `Future[Either[...]]`.

**Comment by bytecodeguru** [comment]
@gabro do you confirm that #19 resolved also this issue?

**Comment by gabro** [comment]
Yep, the ExecutionContext is now provided by the specific runtime monad, which is under control of the client.
